# Generated by Django 6.0.2 on 2026-02-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsuchi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
