# Generated by Django 6.0.2 on 2026-02-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsuchi', '0002_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, choices=[('Fantasy', 'FANTASY CATEGORY'), ('Mythic', 'MYTHIC CATEGORY'), ('N/A', 'UNRECOGNIZED CATEGORY'), ('Sci-fi', 'SCI_FI CATEGORY'), ('', ''), ('', '')], default='N/A', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
