# Generated by Django 6.0.2 on 2026-02-26 12:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsuchi', '0003_book_category_alter_book_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Fantasy', 'FANTASY CATEGORY'), ('Mystic', 'MYSTIC CATEGORY'), ('Biography', 'BIOGRAPHY CATEGORY'), ('N/A', 'UNRECOGNISED CATEGORY')], default='N/A', help_text="Категория книги из списка предложенных. Если неизвестна, выберите 'N/A'", max_length=30, verbose_name='Категория книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Описание книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Цена книги в евро. Должно быть больше 0', max_digits=5, null=True, verbose_name='Цена книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(error_messages={'blank': 'Сожалеем, но книгу нельзя создать без названия книги.', 'unique': 'Кажется книга с таким названием уже существует.'}, max_length=125, unique=True, verbose_name='Название книги'),
        ),
        migrations.CreateModel(
            name='AuthorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(null=True)),
                ('personal_website', models.URLField(blank=True, max_length=255, null=True)),
                ('avatar', models.ImageField(upload_to='avatars/')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='tsuchi.author')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(50)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='tsuchi.author')),
            ],
        ),
    ]
